version: '3.5'
services:

    mongo:
      container_name: 'ptt-give-mongo'
      image: mongo
      restart: always
      environment:
        - MONGO_INITDB_DATABASE=ptt-give
      volumes:
        - ./.docker/mongo:/data/db
      ports:
        - "27007:27017"
